### ISSUE TITLE
Error "invalid shape" while running KITTI demo

### ISSUE THREAD

**Issue by KarelLebeda** [yuxng/SubCNN#14]
When I run one of the examples:
`./experiments/scripts/kitti_val_caffenet_rpn.sh $GPU_ID`
I'm getting an error "invalid shape" during "Appending horizontally-flipped training examples". This is my output:
```
./experiments/scripts/kitti_val_caffenet_rpn.sh $GPU_ID
+ set -e
+ export PYTHONUNBUFFERED=True
+ PYTHONUNBUFFERED=True
++ date +%Y-%m-%d_%H-%M-%S
+ LOG=experiments/logs/kitti_val_caffenet_rpn.txt.2016-07-21_16-25-24
+ exec
++ tee -a experiments/logs/kitti_val_caffenet_rpn.txt.2016-07-21_16-25-24
+ echo Logging output to experiments/logs/kitti_val_caffenet_rpn.txt.2016-07-21_16-25-24
Logging output to experiments/logs/kitti_val_caffenet_rpn.txt.2016-07-21_16-25-24
+ ./tools/train_net.py --gpu 0 --solver models/CaffeNet/kitti_val/solver_rpn.prototxt --weights data/imagenet_models/CaffeNet.v2.caffemodel --imdb kitti_train --cfg experiments/cfgs/kitti_rpn.yml --iters 40000
voc_2007_train
...
mot_tracking_test_Venice-1
Called with args:
Namespace(cfg_file='experiments/cfgs/kitti_rpn.yml', gpu_id=0, imdb_name='kitti_train', max_iters=40000, pretrained_model='data/imagenet_models/CaffeNet.v2.caffemodel', randomize=False, solver='models/CaffeNet/kitti_val/solver_rpn.prototxt')
[0.25, 0.3125, 0.375, 0.4375, 0.5, 0.625, 0.75, 0.875, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]
[0.25, 0.3125, 0.375, 0.4375, 0.5, 0.625, 0.75, 0.875, 1.0, 1.25, 1.5, 1.75, 2.0, 2.25, 2.5, 2.75, 3.0]
Using config:
{'DEDUP_BOXES': 0.0625,
...
 'USE_GPU_NMS': True}
Loaded dataset `kitti_train` for training
Appending horizontally-flipped training examples...
Traceback (most recent call last):
  File "./tools/train_net.py", line 80, in <module>
    roidb = get_training_roidb(imdb)
  File "/vol/vssp/tragic/track2/SubCNN/fast-rcnn/tools/../lib/fast_rcnn/train.py", line 110, in get_training_roidb
    imdb.append_flipped_images()
  File "/vol/vssp/tragic/track2/SubCNN/fast-rcnn/tools/../lib/datasets/imdb.py", line 121, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()
  File "/vol/vssp/tragic/track2/SubCNN/fast-rcnn/tools/../lib/datasets/imdb.py", line 74, in roidb
    self._roidb = self.roidb_handler()
  File "/vol/vssp/tragic/track2/SubCNN/fast-rcnn/tools/../lib/datasets/kitti.py", line 122, in gt_roidb
    for index in self.image_index]
  File "/vol/vssp/tragic/track2/SubCNN/fast-rcnn/tools/../lib/datasets/kitti.py", line 331, in _load_kitti_voxel_exemplar_annotation
    overlaps = scipy.sparse.csr_matrix(overlaps)
  File "/vol/vssp/tragic/track2/python/scipy/sparse/compressed.py", line 66, in __init__
    self._set_self( self.__class__(coo_matrix(arg1, dtype=dtype)) )
  File "/vol/vssp/tragic/track2/python/scipy/sparse/coo.py", line 184, in __init__
    self.shape = M.shape
  File "/vol/vssp/tragic/track2/python/scipy/sparse/base.py", line 74, in set_shape
    raise ValueError('invalid shape')
ValueError: invalid shape
```

I'm running it on Ubuntu 12.04 with python 2.7.

edit: I dug into it and it seems that this is caused by all the objects in the file being read (KITTI/voxel_exemplars/validation/000001.txt) having subclass = -1. This is however rather common, especially in images with fewer objects...

**Comment by yuxng** [comment]
if subclass == -1, the code would not read this line. The problem is in this line: overlaps = scipy.sparse.csr_matrix(overlaps). Can you check the value of "overlaps" when the error happens? Please also try to upgrade the version of scipy as I saw some problem before with an old version.

**Comment by KarelLebeda** [comment]
Well, it's empty, as all the objects inside have subclass -1 (it prints just as []). I updated my scipy to version to 0.17.1 and it seems to work. Thanks!
