### ISSUE TITLE
one Exception about  scipy.sparse.vstack

### ISSUE THREAD

**Issue by zhoutengteng** [yuxng/SubCNN#8]
Traceback (most recent call last):
  File "./tools/train_net.py", line 82, in <module>
    roidb = get_training_roidb(imdb)
  File "/home/zhoutengteng/SubCNN/fast-rcnn/tools/../lib/fast_rcnn/train.py", line 110, in get_training_roidb
    imdb.append_flipped_images()
  File "/home/zhoutengteng/SubCNN/fast-rcnn/tools/../lib/datasets/imdb.py", line 124, in append_flipped_images
    boxes = self.roidb[i]['boxes'].copy()	
  File "/home/zhoutengteng/SubCNN/fast-rcnn/tools/../lib/datasets/imdb.py", line 74, in roidb
    self._roidb = self.roidb_handler()
  File "/home/zhoutengteng/SubCNN/fast-rcnn/tools/../lib/datasets/kitti.py", line 488, in region_proposal_roidb
    roidb = datasets.imdb.merge_roidbs(rpn_roidb, gt_roidb)
  File "/home/zhoutengteng/SubCNN/fast-rcnn/tools/../lib/datasets/imdb.py", line 321, in merge_roidbs
    a[i]['gt_overlaps'] = scipy.sparse.vstack([a[i]['gt_overlaps'],  b[i]['gt_overlaps']])
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 454, in vstack
    return bmat([[b] for b in blocks], format=format, dtype=dtype)
  File "/usr/lib/python2.7/dist-packages/scipy/sparse/construct.py", line 533, in bmat
    raise ValueError('blocks[%d,:] is all None' % brow_lengths.argmin())
ValueError: blocks[1,:] is all None
---------------------------------------------------------------------------------------------
I follow your steps, then  I exec the command
./experiments/scripts/kitti_val_caffenet_rcnn_multiscale.sh 1

 b[i]['gt_overlaps']: ==> 'gt_overlaps': <0x4 sparse matrix of type '<type 'numpy.float32'>' with 0 stored elements in Compressed Sparse Row format>
then i see the shape[0] is 0

in the /fast-rcnn/lib/datasets/imdb.py
```
 @staticmethod
 def merge_roidbs(a, b):
     .......
     a[i]['gt_overlaps'] = scipy.sparse.vstack([a[i]['gt_overlaps'],  b[i]['gt_overlaps']])
```

so how to solve this? Thanks.

**Comment by yuxng** [comment]
Please update your scipy version the newest one.

**Comment by zhoutengteng** [comment]
I update the scipy version，but  it doesn't work

**Comment by litingfeng** [comment]
@zhoutengteng hey, have you solve it ?

**Comment by zhoutengteng** [comment]
@litingfeng  I add this line 'if b[i]["boxes"].shape[0] == 0: continue;'  to the code. But  I haven't get the idea about why there will be some boxes shape (the shape equals 0)

**Comment by litingfeng** [comment]
@zhoutengteng I fixed it, thanks anyway.

**Comment by rita5022** [comment]
@zhoutengteng hi, I met the same question yesterday, could you tell me where did you add the line "if b[i]['boxes'].shape[0] == 0: continue;" in the file imdb.py? 
Is it in the "def merge_roidbs(a, b)", and under the line "a[i]['boxes'] = np.vstack((a[i]['boxes'], b[i]['boxes']))"?
thanks a lot!

**Comment by brjeon** [comment]
After updating the scipy as following, I solved this problem.
sudo pip install --upgrade scipy
